### PR TITLE
Navbar update to match figma

### LINKED ISSUE #133: Update Navbar to match Updated Figma
Vlad's UI Refresh
https://www.figma.com/file/qushS15h87wjpoXaY6ND4W/DeXter-UI---refresh?mode=dev

### PR DESCRIPTION
**Pull request by nguvictor**
Fixes #133 

Colors need to be tweaked a bit and some padding polish, but I can do that after the first initial reviews on nav update to align figma.
navbar refresh

Note:
Didn't change the default page.tsx that has the current trade page as I didn't want to disturb existing PR's
Placed some filler pages for Landing, Trade, Markets
Landing: We can remove this link and put it at the root, when everyone is ready
Trade: Future location of the trade page, placeholder for now
Markets: Mock out to match Figma

### CODE REVIEW

**Comment by EvgeniiaVak** [comment]
I think some of this PR (making it a bit more like figma, even though we won't have markets or community tabs yet) can still probably go into the MVP:
- trade tab (even though it's the only one we have so far... we'll just add others later)
- removing DEXTER from Navbar
- hiding the theme button
- fixing paddings

@nguvictor would you like to continue working on it?

**Comment by nguvictor** [comment]
Yep, I'll can finish it up the PR.

Personally, I was debating on leaving the DEXTER, so that any screenshots have the name for people to look up or share. Otherwise there are no places where you can see the DEXTER name brand only logos at the moment.

I'll follow the figma for now, we can tweak later if anything

**Comment by EvgeniiaVak** [comment]
Yeah, we can leave DEXTER as is, it's not like navbar is overpopulated right now.

**Review by EvgeniiaVak — CHANGES_REQUESTED** [review]
DEXTER looks somewhat out of place... maybe it's the underlining on hover (which is different from the rest of the tabs)... it's ok that something is different about that link to home, but idk looks small compared to the trade and market. Maybe making font size larger on hover (with transition and font size tailwind classes)?

Also maybe a bit larger spacing between the logo image and DEXTER

**Comment by fliebenberg** [comment]
I also like the DEXTER when there is space. We can hide it on mobile screen sizes. Agree that it needs to be bigger. I am not sure if we are looking at the same figma files, but the figma files from the linktree links shows the DEXTER a bit bigger, so I would just go with something similar to that.

**Comment by fliebenberg** [comment]
Here is the link to the figma files that is being used for this PR: https://www.figma.com/file/qushS15h87wjpoXaY6ND4W/DeXter-UI---refresh?mode=dev

**Comment by nguvictor** [comment]
I made the changes suggested by the both of you.
Wasn't sure about the text changing size.

**Review by EvgeniiaVak — APPROVED** [review]
yeah, changing size looked weird, thank you for not adding it 👍

**Pull request merged**
