### PR TITLE
[BUGFIX] Rewards page screen issue solved

### PR DESCRIPTION
**Pull request by Anureng**
Rewards page screen issue solved (#390)

### CODE REVIEW

**Review by dcts — CHANGES_REQUESTED** [review]
Thanks for the fix.

You have 2 formatting changes in this PR, I suspect they were dona automatically by your ide. Please revert those. You can run `npm run lint` and see the issues outlined:

```
> dexter-dapp@0.1.0 lint
> next lint

./src/app/rewards/page.tsx
130:15  Error: Delete `··`  prettier/prettier
131:1  Error: Delete `··`  prettier/prettier
202:123  Error: Insert `⏎········`  prettier/prettier
205:1  Error: Delete `··`  prettier/prettier
```

I recommend you setup your linter to follow the lint configurations of this project, see here:
https://github.com/DeXter-on-Radix/website/blob/main/CONTRIBUTING.md?plain=1#L9-L10

**Comment by Anureng** [comment]
I check all the issue and solved it .

Thank you for your guidance . I really appreciate it

**Review by dcts — APPROVED** [review]
Thanks fir fixing this 🙏🎉 
It might take some time for us to merge this PR, as we have a problem with out CI that needs to be solved in order for us to merge. But feel free to tackle another issue if you want! 

If you have any questions feel free to reach out to me either on discord (dcts_) or telegram (dctsdev).

**Comment by fliebenberg** [comment]
@Anureng Thanks for tackling this issue. I will wit until we can deploy and test before approving, but feel free to tackle other issues issues in the meantime.

**Review by dcts — APPROVED** [review]

**Review by nguvictor — APPROVED** [review]

**Pull request merged**
