### PR TITLE
[Fix]: Wrong pair selector values

### PR DESCRIPTION
**Pull request by restylianos**
Resolves [268](https://github.com/DeXter-on-Radix/website/issues/268)

### CODE REVIEW

**Comment by dcts** [comment]
Deploy Preview is here:
https://restylianos-pair-selector-sy.dexter-1we.pages.dev/

When I try it on testnet on mobile, the issue still occures. For example, in this video I open the pair selector and then select Adex/xrd but it doesnt work. Then I select cuppa/xrd next but it changes to adex/xrd.


https://github.com/DeXter-on-Radix/website/assets/44790691/88e1d180-820a-44ac-901e-2fecdff4ffec

**Comment by dcts** [comment]
Awesome, this fixes the issue for me! Well done!
🎉🔥

Will review the code when I get home but its great to see this bug resolved, especially as radix wallet will soon be available for mobile!

**Comment by restylianos** [comment]
The issue was that the onmouseenter event is not triggered in the same way across mobile and desktop devices. I would expect to have a never working filtering selector on mobile devices but it seems that the first time that an option is selected the onhover event is triggered and then the click event which is the same as the ??mouseenterevent?? (I am not sure if this is true since i cannot find a specific article which explains what happens in this scenario. I will update my comment if I manage to find anything relevant to this specific case). Based on the previous code version the onMouseEnter event was used on each option in order to change the highlighted index. After that, the selectOption function was relying on highlighted index in order to "perform" an element selection which was leading to the selection of a wrong element `const option = filteredOptions[highlightedIndex]`.

**Comment by nguvictor** [comment]
I've had this intermittently happen on desktop as well, thanks for the fix!

**Review by nguvictor — APPROVED** [review]

**Comment by restylianos** [comment]
> I've had this intermittently happen on desktop as well, thanks for the fix!

@dcts This was due to the useEffect sync issue

**Review by dcts — APPROVED** [review]

**Pull request merged**
