### PR TITLE
Pair selector imporvements

### LINKED ISSUE #154: Pair selector improvements
- [x] search for pairs
- [ ] shortcuts: to start search, select on enter, cancel on esc 
- [x] auto-close when a pair is selected
- [ ] fix vertical alignment
- [x] (maybe) improve the background animation on click

### LINKED ISSUE #219: Token Selection Drop Down UI Issue with "i" tooltip on Post Only
image

### PR DESCRIPTION
**Pull request by EvgeniiaVak**
fixes #219
fixes #154

- fixes strange bottom margin
- adds shortcuts for search - `/`, enter, esc, arrows
- fixes the (i) info label showing up on top of the options
- adds scrollbar (not visible unless we have more pairs)

### CODE REVIEW

**Review by Radstakes — APPROVED** [review]
This is great Ev, I like the keyboard shortcut and the search function will be really useful as we list more pairs.  I can't read the code but the preview works great so approving on that basis.

**Review by nguvictor — APPROVED** [review]

**Comment by nguvictor** [comment]
Minor might be better as as different issue, but I get an auto complete that pops up. Might be my browser though
image

**Comment by EvgeniiaVak** [comment]
@nguvictor yeah, the popup looks weird, maybe I can disable it somehow, what's your browser?

**Comment by nguvictor** [comment]
It's Brave browser 
image

**Pull request merged**
