### PR TITLE
Add multi language support (i18n)

### LINKED ISSUE #287: Add multi-language capability for website.
There has been a request for a Portuguese version of the Dexter website given that the majority f current users are from Portuguese speaking countries.
It might make sense to add this capability sooner rather than later as it will require a rework of the existing codebase and is easier done while the code base is still relatively small.
Once it is done, it becomes much easier to add more languages and it also ensures that future additions to the website automatically allows for multi-language.

### PR DESCRIPTION
**Pull request by dcts**
fixes #287.

This PR adds a client side implementation of i18n, it includes:
- client site internationalization, using custom react hook and i18n redux state (for reasoning see this thread: https://discord.com/channels/1125689933735145503/1218244739363766302)
- translation to portuguese (PT) and using english (EN) as default
- full translation of all text, organized in namespaces which are organized by pages/components (e.g. trade, footer) or logically (enums, errors)
- automatic language detection from browser 
- language selection UI in top right corner
- translation json files are structured in the same way as server side rendered i18n libraries require it, to simplify transition into SSR i18n (in case we decide to do that). The custom react hook also mimicks the i18n libraries by using `t('conetnt_key')` syntax.
- developer documentation on how to use internationalization
- test to ensure all keys in translation files are the same (prevent typos)

image

### CODE REVIEW

**Comment by fliebenberg** [comment]
This is great work! Well done. I would like to preview the changes, but there is no preview options showing like they normally do for PRs? Do I need to do something different now?

**Comment by dcts** [comment]
@fliebenberg thanks! Yes I miss the deploy preview as well. I requested access to cloudflare from @Radstakes but am also not sure how to create deploy previews with cloudflare, will find out and ping once a preview is available.

**Comment by dcts** [comment]
@fliebenberg here is the deploy preview:
https://i18n-static-preload.dexter-1we.pages.dev/

**Comment by fliebenberg** [comment]
You have missed the "COUNT" in the "ORDER COUNT" column of the orderbook panel.
Also, the Slippage Limit input box changes its width to fit the heading. I would probably suggest we give the box a max width that makes sense rather than just expanding to the width of the heading.

**Comment by fliebenberg** [comment]
In anticipation of even more languages being added now that we have the capability built, I would suggest you make the language selection a dropdown box with the currently selected language code showing in the navbar e.g. EN. In the dropdown selection box, show both the language code and language name e.g. EN - English, PT - Portuguese etc.

**Comment by dcts** [comment]
@fliebenberg updated the following things to address your comments:
1. fixed slippage input size (max-width 100px)
2. added translation for ORDER COUNT. 

Updated deploy preview:
https://i18n-static-preload.dexter-1we.pages.dev/

Please test these features:
1. The site automatically displays in Portuguese if your browser's default language is set to pt.
2. Change languages via the top-right menu; this preference is saved locally and remembered on future visits.
3. Clearing your browser's data (cookies) resets the language setting.

Concerning the UI change for the language selection (dropdown): I suggest to tackle this in a future PR. The same with translation improvements. Even if translation is not perfect yet, it's already a huge improvement and brings value to the brazilian community. Also this PR is directly blocking the deploy of the buy/sell panel which I'm working on in parallel (will need to resolving merge conflicts). So My proposal is to:
-> merge this PR
-> resolve merge conflicts with buy/sell panel
-> push PR buy/sell panel
-> once submitted tackle dropdown and translation improvements :)

WDYT?

**Comment by dcts** [comment]
- [x] Fixed all wrong language translations
- [ ] get approval from portuguese speaking community member

**Review by fliebenberg — APPROVED** [review]
Happy.

**Comment by nguvictor** [comment]
Not, blocking the deployment, but would be a good fix for the future for the missing translations:
image

**Review by nguvictor — APPROVED** [review]

**Comment by dcts** [comment]
@nguvictor great catch! I purposefully did not fix those translations, as the buy/sell panel is redesigned and the error messages will be refactored again, so this will be fixed with buy/sell panel UI redesign PR. 

Thanks for review!

**Pull request merged**
