### PR TITLE
Add runs on radix button

### LINKED ISSUE #183: Add "Runs on Radix" to footer
Related to Telegram suggestion:
https://t.me/c/1988854086/1/812

### PR DESCRIPTION
**Pull request by dcts**
Added "Runs on Radix" button to the end of the footer. I know we have already "runs on RADIX" as text in the footer, but the button looks super cool IMO.

runsonradix-banner-before-after

Fixes #183

### CODE REVIEW

**Comment by EvgeniiaVak** [comment]
Prettier (formatter) checks fail in this PR. @dcts could you fix those please? You can replicate them locally with `npm run lint`

```
ev@mac website % npm run lint

> dexter-dapp@0.1.0 lint
> next lint


./src/app/components/Footer.tsx
52:13  Error: Replace `⏎············href="https://www.radixdlt.com/"⏎············target="_blank"` with `·href="https://www.radixdlt.com/"·target="_blank">`  prettier/prettier
55:11  Error: Replace `>` with `··<img`  prettier/prettier
56:13  Error: Replace `<img·width="150"·src="runs-on-radix.png"·alt="Runs·on·Radix·Button"` with `··width="150"⏎··············src="runs-on-radix.png"⏎··············alt="Runs·on·Radix·Button"⏎············`  prettier/prettier

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
```

If you are using vscode you can install recommended extensions (from `.vscode/extensions.json`), they will highlight the errors directly while you're editing.

**Review by EvgeniiaVak — CHANGES_REQUESTED** [review]
lint errors

**Comment by dcts** [comment]
Fixed all lint errors. Thanks for the pointers.

**Review by EvgeniiaVak — APPROVED** [review]

**Comment by EvgeniiaVak** [comment]
I like it. But we will have Runs on Radix 2 times in the footer... maybe removing it from the text? Also, @fliebenberg do you have something similar for AlphaDEX?

**Comment by dcts** [comment]
What about this?
Bildschirmfoto 2024-02-01 um 21 52 00

But IMO having "runs on radix" twice as proposed in this PR does not hurt. And might be even good for SEO purposes (when people search for "apps that run on radix"). 

But happy to change, up to you :)

**Comment by fliebenberg** [comment]
> I like it. But we will have Runs on Radix 2 times in the footer... maybe removing it from the text? Also, @fliebenberg do you have something similar for AlphaDEX?

I do not currently have a "Built on AlphaDEX" button, but would really like one, so I have put out a challenge in the community for someone to design one for me. WIll let you know once I have it.

**Comment by EvgeniiaVak** [comment]
> What about this? Bildschirmfoto 2024-02-01 um 21 52 00
> 
> But IMO having "runs on radix" twice as proposed in this PR does not hurt. And might be even good for SEO purposes (when people search for "apps that run on radix").
> 
> But happy to change, up to you :)

I'm also happy either way 😃 if it helps with SEO - let's leave 2 runs on radix 👍

**Comment by Kafkafrate** [comment]
I would keep them simple if you want to add the labels. 
To have them both just white on black. Radix has a version like that. 
Otherwise I think it gets too "flower power" the whole footer.

**Review by nguvictor — APPROVED** [review]

**Pull request merged**
