### PR TITLE
fixed wrong currency used in price info

### LINKED ISSUE #356: Wrong price currency for XRD/xUSDC
The price should always be in second token terms. So in this case I'd expet the price to be in "xUSDC", not "XRD".

image

### To reproduce:
- open dexteronradix
- switch to XRD/xUSDC pair

### PR DESCRIPTION
**Pull request by flamerged**
- Fixes #356

### CODE REVIEW

**Review by dcts — APPROVED** [review]
Awesome, Looks good to me! 
Welcome to Dexter! :)

**Review by EvgeniiaVak — APPROVED** [review]
cool! thanks and welcome

**Comment by EvgeniiaVak** [comment]
@Radstakes could you take a look into this? Cloudflare Pages Expected — Waiting for status to be reported maybe it needs to be manually triggered somewhere on cloudflare? I can disable this check to be required on GitHub pull requests, if it's so (and only require `Lint and Test` check to be completed before it can be merged).

**Comment by Radstakes** [comment]
> @Radstakes could you take a look into this? Cloudflare Pages Expected — Waiting for status to be reported maybe it needs to be manually triggered somewhere on cloudflare (maybe because it's from a fork)? Alternatively, I can disable this check to be required on GitHub pull requests and only require `Lint and Test` check to be completed before it can be merged.

I'm not sure why this isn't working.  Could it be that it needs to be committed to a non-protected branch first as per this?

image


It doesn't seem to have been picked up by CloudFlare at all so I can't deploy it manually.  Perhaps it could be re-committed or this check removed so we can merge it?

**Comment by flamerged** [comment]
> > @Radstakes could you take a look into this? Cloudflare Pages Expected — Waiting for status to be reported maybe it needs to be manually triggered somewhere on cloudflare (maybe because it's from a fork)? Alternatively, I can disable this check to be required on GitHub pull requests and only require `Lint and Test` check to be completed before it can be merged.
> 
> I'm not sure why this isn't working. Could it be that it needs to be committed to a non-protected branch first as per this?
> 
> image
> 
> It doesn't seem to have been picked up by CloudFlare at all so I can't deploy it manually. Perhaps it could be re-committed or this check removed so we can merge it?

shouldn't it be possible to restart checks?

**Comment by flamerged** [comment]
I [read](https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported) that you can just close and reopen the pr for it to work and I did so. Now it needs approval again.

**Comment by Radstakes** [comment]
@EvgeniiaVak - I removed this check to get this one committed and have reapplied the check.  Let's see if it happens again or if it's just a one-off workflow bug.

**Pull request merged**
