### PR TITLE
Test e2e

### LINKED ISSUE #20: tests ci check for PRs

### LINKED ISSUE #31: Add tests
Auto tests with playwright or cypress for different browsers (at least chrome, firefox, safari) that check basic app functionality.

### PR DESCRIPTION
**Pull request by EvgeniiaVak**
fixes #31 
fixes #20 
Runs tests before a PR gets merged if a PR breaks the build it will not pass the checks and we won't be able to merge.

### WHY?
Because once we have something deployed for the people to test it will be desirable to keep it working at all times, and we are deploying test version automatically from every commit to the main branch. We've seen during development that while locally with `npm run dev` everything works fine, when we run `npm run build` something breaks. 

These tests ensure that the project builds successfully and that all the major browsers that we support can render the page (later, after the MVP we will have more checks for components to not break).

Another reason is having feedback asap - we are an asynchronous team or part-timers from various time zones, if some feedback can be given automatically, without waiting for a reviewer to check - we should utilize that.

### CODE REVIEW

**Review by SmashingBumpkin — COMMENTED** [review]
I've had a look over this and everything looks sensible, and the site also runs and builds, however I am not at all familiar with this framework.

**Comment by EvgeniiaVak** [comment]
@SmashingBumpkin could you approve? Or if you see why not merging it, please tell.

**Comment by EvgeniiaVak** [comment]
@abdulhaseeb13mar I don't want to update OrderInput in this PR, because it will likely cause code conflicts with OrderInput updates @SmashingBumpkin is working on, so the image alt warnings will still be here. As for console - we are using it to show errors, so I updated eslint to reflect that.

**Comment by EvgeniiaVak** [comment]
@fliebenberg could you please review this one? 

I know you probably think tests are better done post-mvp, but I ask you to kindly reconsider - testing (I mean manually by other people, not just devs) is very important to be started as early as possible (you've seen the fruits of this already by my and Faraz's bug reports in discord), not all bugs are easily discoverable, we need as much time spent on it as possible. 

And if we will have a broken `main` branch it will make testing less efficient, this PR aims to drastically increase the probability that the `main` branch is working at all times after new PRs are merged.

**Comment by EvgeniiaVak** [comment]
By now I think Fred is not going to review this 😆 And I don't want to review other PRs and check manually every time that the build is working in all browsers - until this one is either merged or closed. 

@SmashingBumpkin besides Fred you are the only one who can approve this PR, could you please approve if you think it's good to go in? Or close it if you think it's not. I know you didn't work with playwright before, but it does nothing complicated - takes the build, launches on port 3000, currently it tests that the page loads at all and that it connects to AlphaDEX.

**Comment by fliebenberg** [comment]
> By now I think Fred is not going to review this 😆 And I don't want to review other PRs and check manually every time that the build is working in all browsers - until this one is either merged or closed.
> 
> @SmashingBumpkin besides Fred you are the only one who can approve this PR, could you please approve if you think it's good to go in? Or close it if you think it's not. I know you didn't work with playwright before, but it does nothing complicated - takes the build, launches on port 3000, currently it tests that the page loads at all and that it connects to AlphaDEX.

I am happy for someone else to review. I certainly believe in tests especially in a case like this where it makes deployment quicker. I just dont have the bandwidth now to have a look at this, so would be better if someone else could.

**Review by Radstakes — APPROVED** [review]
Approving this. Testing that nothing breaks before merging is crucial for our auto deployment

**Pull request merged**
