### PR TITLE
[BUGFIX] Prevent claiming rewards when button is disabled

### LINKED ISSUE #401: Rewards page claim rewards button shows as disabled but it's actually not
**Step to reproduce:**
Connect your wallet to the Rewards page, while you do not have any rewards.
Approve on the wallet app.

**Excpected:** None rewards appear on the webpage. The "claim ALL rewards" button is not clickable
**Actual:** :The button is grayed out but it's still clickable.
When I click the button it's initiated a trx on my wallet app.
image

### PR DESCRIPTION
**Pull request by dcts**
fixes #401.

### CODE REVIEW

**Review by fliebenberg — APPROVED** [review]

**Comment by yuliaSharabi** [comment]
I am unable to test it with the preview URL - as we do not support wallet connection in preview. Or I do need some additional settings in order to retest the bug?

**Comment by nguvictor** [comment]
> we do not support wallet con

It should work, are you using the stokenet version of the wallet?

**Comment by nguvictor** [comment]
@dcts I tried connecting with wallet, but got a bunch of errors. Maybe we are missing envs?
image

**Comment by dcts** [comment]
@nguvictor @yuliaSharabi yes the env variables on deploy preview seem to lack the correct claim_component address it seems. To test this, can you instead fetch and checkout this branch locally and use the following mainnet env variables to test:
```
NEXT_PUBLIC_NETWORK=mainnet
NEXT_PUBLIC_DAPP_DEFINITION_ADDRESS=account_rdx168qrzyngejus9nazhp7rw9z3qn2r7uk3ny89m5lwvl299ayv87vpn5
NEXT_PUBLIC_DEFAULT_PAIR_ADDRESS=component_rdx1czgjmu4ed5hp0vn97ngsf6mevq9tl0v8rrh2yq0f4dnpndggk7j9pu
NEXT_PUBLIC_CLAIM_COMPONENT=component_tdx_2_1czzn503fzras55wyrs9zczxrtvf8fpytmm52rc5g3hsyx9y5dv9zzs
```

**Comment by nguvictor** [comment]
> @nguvictor @yuliaSharabi yes the env variables on deploy preview seem to lack the correct claim_component address it seems. To test this, can you instead fetch and checkout this branch locally and use the following mainnet env variables to test:
> 
> ```
> NEXT_PUBLIC_NETWORK=mainnet
> NEXT_PUBLIC_DAPP_DEFINITION_ADDRESS=account_rdx168qrzyngejus9nazhp7rw9z3qn2r7uk3ny89m5lwvl299ayv87vpn5
> NEXT_PUBLIC_DEFAULT_PAIR_ADDRESS=component_rdx1czgjmu4ed5hp0vn97ngsf6mevq9tl0v8rrh2yq0f4dnpndggk7j9pu
> NEXT_PUBLIC_CLAIM_COMPONENT=component_tdx_2_1czzn503fzras55wyrs9zczxrtvf8fpytmm52rc5g3hsyx9y5dv9zzs
> ```

Hey, you might of made a typo on the last address for mainnet it should be 
NEXT_PUBLIC_CLAIM_COMPONENT=component_rdx1cptrclw8gzm55866nas8el9jcfa8j3se7ch0fz9uq498mgy0ngn4ft

**Review by nguvictor — APPROVED** [review]

**Comment by yuliaSharabi** [comment]
Not sure I understand the instructions. If I checkout the branch do I use stokenet for it? Is it on mainnet already so we can test it on mainnet, as I see it was merged?

**Comment by dcts** [comment]
> Is it on mainnet already so we can test it on mainnet

Yes its on mainnet so you can test using dexteronradix.com/rewards

**Comment by yuliaSharabi** [comment]
@dcts Retested sucsessfully! Issue can be closed.

**Pull request merged**
